### PR TITLE
Upgrade JGit to 4.6.1.201703071140-r

### PR DESCRIPTION
**Pull request by bchazalet**
@dwijnand I am trying to squeeze a last upgrade of JGit before you release.

### CODE REVIEW

**Comment by dwijnand** [comment]
@bchazalet have a look, Travis CI failed. Java versions?

**Comment by bchazalet** [comment]
indeed. I am trying to find out whether the newest versions of JGit require java 8 but I didn't think that was the case.

**Comment by bchazalet** [comment]
JGit 4.6 does [require](https://wiki.eclipse.org/JGit/New_and_Noteworthy/4.6) java 8, so I suggest that we should not merge this yet.

**Comment by bchazalet** [comment]
i.e. we should *at least* get an updated release out first, before considering the upgrade to java 8.

**Comment by hseeberger** [comment]
I agree to both: Let's get a v0.9 out and then move on towards v1.0 (maybe with some more iterations) requiring Java 8.

**Comment by dwijnand** [comment]
Yeah that's what I expected. Thanks for looking into it.

I've run out of time today sadly. I'll cut a release with the status quo tomorrow.

**Comment by oliverlockwood** [comment]
@dwijnand @hseeberger can I suggest this PR gets closed, as it's become redundant now that #148 has been merged?

**Comment by dwijnand** [comment]
Makes sense.

**Pull request closed without merging**
