### PR TITLE
Add shim for sbt 1.0.0-M6 compat

### PR DESCRIPTION
**Pull request by eed3si9n**

### CODE REVIEW

**Comment by dwijnand** [comment]
Travis CI failed because your shim is for M6, but Travis is configured for M5.

**Comment by larsrh** [comment]
This seems to be redundant now; 1.0.x support has been added some time before 744a513f164a817546cada6956288f4f45b91678.

**Comment by eed3si9n** [comment]
Maybe we should still save https://github.com/sbt/sbt-git/pull/134/commits/287edac5bd056f71c87320557b83c28b7bc42c9e so we don't have to keep creating Bintray packages.

**Comment by dwijnand** [comment]
#137.

**Pull request closed without merging**
