### PR TITLE
Automate releases with sbt-release

### PR DESCRIPTION
**Pull request by leonardehrenfried**
Since the version is now being read from `version.sbt` this plugin doesn't depend on itself anymore.

The release process also includes a step where a marker line is searched for in the README file and the following line is replaced, thereby putting the latest version into the README, too.

### CODE REVIEW

**Comment by bchazalet** [comment]
I didn't know you could update the readme file's version, that's powerful!

**Comment by leonardehrenfried** [comment]
Sorry, I must have overlooked your question.

The command is: `sbt release`

**Comment by francisdb** [comment]
I guess this needs to be updated to do a cross-sbt (0.13.x, 1.0.x) release?

**Comment by nhooey** [comment]
@bchazalet Can you get this merged and released?

**Comment by SethTisue** [comment]
superseded by #185

**Pull request closed without merging**
