### PR TITLE
Upgrade jgit to 5.11.0.202103091610-r

### LINKED ISSUE #161: Wrong `git describe` version is being chosen
I am trying the following build settings:

```
    git.useGitDescribe := true,
    git.gitTagToVersionNumber := { tag: String =>
      if (tag matches "[0-9]+\\..*") Some(tag) else None
    },
    git.uncommittedSignifier := None
```

Everything was working as expected for several versions (i.e. 1.5, 1.6, 1.7, 1.8, 1.9). As soon as I bumped my tag to "1.10", the detected version got stuck on "1.9". I bumped the tag to "1.11", the version I'm getting from sbt-git is still "1.9". `git describe` in both the project directory and via the sbt shell is showing me "1.11".

How can I debug this?

### PR DESCRIPTION
**Pull request by jsyeo**
With this, we could fix #161

### CODE REVIEW

**Comment by lightbend-cla-validator** [comment]
Hi @jsyeo,

Thank you for your contribution! We really value the time you've taken to put this together.

Before we proceed with reviewing this pull request, please sign the Lightbend Contributors License Agreement:

[https://www.lightbend.com/contribute/cla](https://www.lightbend.com/contribute/cla)

**Comment by jason-yeo-paidy** [comment]
@dwijnand ping 😊

**Comment by jsyeo** [comment]
@dwijnand ping 😄

**Comment by SethTisue** [comment]
@jsyeo are you pretty confident this should be merged, or do you have any doubts you'd like to bring up with reviewers?

**Comment by jsyeo** [comment]
> are you pretty confident this should be merged, or do you have any doubts you'd like to bring up with reviewers?

Yes, I think this should be merged. I don't think there should be any problems with merging this.

**Pull request merged**
