### PR TITLE
Allow the use of specific tag matching when using gitDescribe functionality

### LINKED ISSUE #133: Allow use of prefixes for `useGitDescribe` case.
## Background:
-  Multi-module project, where I want to release submodules separately, tag them accordingly, and base versioning on tags with separate prefixes
-  In Gradle world, I would use the [Axion-release plugin](http://axion-release-plugin.readthedocs.io/en/latest/) and configure the `prefix` property.
-  In SBT world, I can use `sbt-release` for the release logic, but for deriving version numbers implicitly from tags `sbt-git` is the place to go.

## Diving into the details in `sbt-git`:
-  Under the covers, using `useGitDescribe` invokes the equivalent of `git describe --tags`, as documented [here](https://github.com/sbt/sbt-git/blob/master/src/main/scala/com/typesafe/sbt/SbtGit.scala#L21,L28).  For my project which includes two submodules `adapters` and `transformers`, this will always give me the tag of whatever was most recently released, rather than the one I'm interested in, for example:
```bash
    $ git describe --tags
    adapters-0.28.0-2-g4bc98ad
```
-  What I would like to do is to be able to configure `sbt-git` to set a *tag prefix* based on which module I'm interested in.  Under the covers, this could use `git describe`'s native regex matching, i.e.
```bash
    $ git describe --tags --match "transformers-*"
    transformers-0.22.0-5-g4bc98ad
    $ git describe --tags --match "adapters-*"
    adapters-0.28.0-2-g4bc98ad
```
-  An alternative (which I originally was looking at) would be to use a custom `gitTagToVersionNumber` function.  However, the tags passed to this function by `sbt-git` are only the ones that explicitly match the current commit - the `gitCurrentTags` value [filters out any tag whose associated commit does not exactly match the commit at HEAD](https://github.com/sbt/sbt-git/blob/master/src/main/scala/com/typesafe/sbt/git/JGit.scala#L67) - so it doesn't find "closest match" tags in the way that `git describe` does.
-  However, I do notice that `JGit` doesn't yet support the `--match` functionality.

## Next steps
I need this functionality, so I'll probably go down the road of implementing it myself.  Rather than have it just a local change, I'd prefer to contribute it back as I imagine other developers may find it useful.  To this end:
-  Are you interested in having this functionality publicly available in `sbt-git`?
-  If so:
    -  how would you prefer to have it configured?
    -  how would you prefer to have it implemented?  I guess the ideal would be to add explicit JGit support for `--match`, and then use that; however it may be quicker to implement the `--match` functionality locally.  Or alternatively, you may prefer to update the `gitCurrentTags` functionality to return all tags that relate to the current commit's history, rather than just to the current commit itself.

Thanks for your time in reading this.

### PR DESCRIPTION
**Pull request by oliverlockwood**
Closes #133.

As per the example that the test case provides, and the documentation added to the README, this allows people to specify a glob match for `git describe`'s `--match` functionality, so we find the first *matching* tag and interpret that, rather than just finding the first tag.

### CODE REVIEW

**Comment by oliverlockwood** [comment]
@dwijnand @hseeberger I'd be grateful for a review of this PR, when you have the chance.  Many thanks.

**Comment by oliverlockwood** [comment]
@dwijnand I believe the changes are backwards compatible in terms of the external API.  There's a new optional setting `gitDescribePatterns`; if this isn't provided, the behaviour is unchanged.

Or did you mean the internal API defined by the `ReadableGit` trait?

**Comment by dwijnand** [comment]
Yeah `ReadableGit` (and to an extent `JGit`), which I'm not sure if it's clearly de-marked as "internal API".

**Comment by oliverlockwood** [comment]
@dwijnand (and @bchazalet and @hseeberger, since you were both kind enough to work with me on previous PRs in this repo): Could you please make a call on whether or not you want to mandate back-compatibility on the `ReadableGit` interface?  Then we can hopefully either get this merged as-is, or I'll have the prompt to make the minor fix necessary.  Thanks! 😃

**Comment by nhooey** [comment]
@dwijnand Could you merge this pull request and release?

**Comment by dwijnand** [comment]
I expect preserving backwards compatibility wouldn't be too hard, so I think the cost is worth the reward of not accidentally breaking existing builds/plugins.

@oliverlockwood do you have time to look into that, by chance?

**Comment by oliverlockwood** [comment]
@dwijnand I've rebased from the latest `master` and then updated the original commit, to add a default value to the function.  This gives partial back-compatibility, as in:
-  you can still call `describedVersion()` without providing parameters.

However:
-  you can't call `describedVersion` without parentheses, as you could before
-  overrides of the `describedVersion()` function would need to be changed, also.

In case you want to go further, I've added a second commit which adds a duplicate function to the trait with no parameters, exactly as before.  The implementation of this in `JGit` delegates to the new function.

Up to you whether you want to merge both commits or only one of them.

Does this cover what you were looking for?

**Comment by dwijnand** [comment]
Hey @oliverlockwood, thank you for coming back to this. I had a slightly different encoding in mind, so instead of ping-ponging with you on it I just pushed another commit with what I had in mind.

I'll merge this tomorrow if it looks good, and hopefully have time to cut a release too.

**Comment by LeifW** [comment]
Could this not be scoped to `ThisBuild` so this could be used to enable different subprojects in a monorepo to have different versions?
e.g. say there's subprojects foo and bar, and the repo is tagged with foo/1.0, bar/1.2; this feature would allow each project to get the right version by setting `git.gitDescribePatterns := Seq(name.value + "/*")` were this not scoped to `ThisBuild`.

**Pull request merged**
