### PR TITLE
Added support for different git describe settings across projects

### LINKED ISSUE #196: Allow different tag patterns for multi-module projects using git describe

### PR DESCRIPTION
**Pull request by liorregev**
Closes #196

### CODE REVIEW

**Comment by SethTisue** [comment]
anyone want to review this PR...?

**Review by raboof — APPROVED** [review]
this looks pretty useful, but unfortunately now conflicts with `main` - could you update? then I'll merge ;)

**Comment by lightbend-cla-validator** [comment]
At least one commit author (lior.regev@placer.ai, lior.regev@placer.ai) is not linked to a user. See https://help.github.com/en/articles/why-are-my-commits-linked-to-the-wrong-user#commits-are-not-linked-to-any-user

**Comment by lightbend-cla-validator** [comment]
At least one commit author (lior.regev@placer.ai) is not linked to a user. See https://help.github.com/en/articles/why-are-my-commits-linked-to-the-wrong-user#commits-are-not-linked-to-any-user

**Comment by liorregev** [comment]
> this looks pretty useful, but unfortunately now conflicts with `main` - could you update? then I'll merge ;)

Done

**Comment by raboof** [comment]
(we still need to remove the CLA checker from this repo, don't worry about it)

**Review by raboof — APPROVED** [review]

**Pull request merged**
