### PR TITLE
Making baseVersion optional

### PR DESCRIPTION
**Pull request by bchazalet**
i.e. making baseVersion a SettingKey[Option[String]] but still defaulting to "1.0" as not to change the current behavior.

Now baseVersion can be left empty:
```
git.baseVersion := None
```

but that means users already overriding baseVersion and willing to upgrade will have to update their build.sbt. 

for issue #41

### CODE REVIEW

**Comment by jsuereth** [comment]
The fix looks good.  I'd like to find a way to not break existing builds though....

I think maybe we can support old builds AND the new syntax, do you mind if I adapt your PR?

**Comment by jsuereth** [comment]
Can you rebase against master? I just submitted a set of scripted tests, and I'd like to make sure PRs pass tests before accepting them in the future.

**Comment by bchazalet** [comment]
sure, no problem to adapt. I have rebased  against master now.

**Comment by jsuereth** [comment]
cool, I have a PR incoming w/ a different approach that should work w/ existing builds.

**Comment by jsuereth** [comment]
closing in favor of backwards compatible PR.

**Pull request closed without merging**
