### PR TITLE
Travis -> GitHub Actions for CI

### LINKED ISSUE #184: Volunteer needed to add CI using GitHub Actions
at https://github.com/sbt/sbt-git/issues/182#issuecomment-824490208, Eugene wrote:

> You can check out https://github.com/sbt/sbt-pgp/tree/develop/.github/workflows for the reference implementation of how to hook up GitHub Actions.

The existing `.travis.yml` should be consulted, since that's what's being replaced.

### PR DESCRIPTION
**Pull request by raboof**
Fixes #184

### CODE REVIEW

**Comment by raboof** [comment]
Does this need to be merged first to be able to run it, or did I miss something else?

**Review by jsyeo — APPROVED** [review]

**Comment by SethTisue** [comment]
> Does this need to be merged first to be able to run it

Yeah, since it comes from a fork. I'll merge it.

**Comment by SethTisue** [comment]
first run: https://github.com/sbt/sbt-git/actions/runs/785799865

**Comment by raboof** [comment]
💚

**Pull request merged**
