### PR TITLE
Perf: Eliminate redundant call to `git.describedVersion`

### PR DESCRIPTION
**Pull request by adpi2**
While I was profiling the loading time of [softwaremill/sttp](https://github.com/softwaremill/sttp) build, I noticed that `sbt-git` takes about half of the CPU time. Indeed it seems that `git.describedVersion` is quite expensive as it needs to unpack Git object directories. The problem is this operation is repeated too many times: once for each sub-project of the build (~200 projects in the case of sttp).

This PR eliminates the redundant calls to `describedVersion`: if the input settings of the `ThisProject` and `ThisBuild` are the same, the project reuses `ThisBuild / gitDescribedVersion` instead of recomputing it.

On [softwaremill/sttp](https://github.com/softwaremill/sttp) it reduces the loading time by 45% (12 seconds instead of 22).

### CODE REVIEW

**Comment by adpi2** [comment]
## Before

sbt-git-cpu

## After

sbt-git-cpu-after

**Comment by adpi2** [comment]
@SethTisue can you review this?

**Review by SethTisue — APPROVED** [review]
great catch!

**Comment by mikegpl** [comment]
Hello, this looks promising in projects I've been working with too - thank you @adpi2 for your contribution and @SethTisue for your quick review ;) I just wanted to kindly follow up and check if there's a timeline for merging and releasing version with these changes.

**Comment by SethTisue** [comment]
re: publishing, I've opened #253

**Pull request merged**
