### PR TITLE
fix for #67

### PR DESCRIPTION
**Pull request by lrytz**

### CODE REVIEW

**Comment by lrytz** [comment]
Proposed fix for #67. It will break things for people currently using the workaround described in #67.

Review by @jsuereth

**Comment by lrytz** [comment]
I was not sure if I should use `defaultTagByVersionStrategy` or `gitTagToVersionNumber` - the latter, when written by a user, might not match the string returned by `git describe`..

**Comment by lrytz** [comment]
green now, @jsuereth

**Comment by jeantil** [comment]
This looks good to me

**Comment by jeantil** [comment]
If I read that correctly it also fixes #89 `if no git tags, can't load project with ``useGitDescribe := true`` `. 
I think the patch is slightly better than #91 but it doesn't have the fix for #90 `uncommitted suffix is also attached on git described version`

@jsuereth think this could make it in sbt-git ?

**Comment by jsuereth** [comment]
LGTM!   I like it.

**Comment by jeantil** [comment]
thanks !

**Comment by lrytz** [comment]
:cake:

**Comment by 2m** [comment]
Can we get a release with this? Failing to load project definition when git repo does not have a tag is really cumbersome for new projects.

**Pull request merged**
