### PR TITLE
Publish snapshots from master/main

### PR DESCRIPTION
**Pull request by raboof**

### CODE REVIEW

**Comment by mkurz** [comment]
@SethTisue If you merge this we should see if the current credentials work or not.

**Review by mkurz — APPROVED** [review]

**Comment by mkurz** [comment]
`java.io.IOException: Server returned HTTP response code: 403`
It seems the credentials are wrong.

**Comment by mkurz** [comment]
Ping @eed3si9n

**Comment by SethTisue** [comment]
let's continue on https://github.com/sbt/sbt-git/issues/211

**Pull request merged**
