### PR TITLE
Release to sonatype from CI

### LINKED ISSUE #185: Volunteer needed to add publishing via sbt-ci-release
because Bintray is gone

at https://github.com/sbt/sbt-git/issues/182#issuecomment-824490208, Eugene wrote:

> You can check out https://github.com/sbt/sbt-pgp/tree/develop/.github/workflows for the reference implementation of how to hook up GitHub Actions.

depends on #184 — we need working CI before we can do publishing

### PR DESCRIPTION
**Pull request by raboof**
Fixes #185

However, the WIP in this branch runs into https://github.com/sbt/sbt-git/issues/185 . We should probably just update to a newer sbt.

### CODE REVIEW

**Comment by raboof** [comment]
It looks like I don't have the rights to add the required entries to the github secrets.

Could someone do that, or give me the rights to do that?

(this is not me volunteering to actively maintain this package, though, sorry ;) )

**Comment by SethTisue** [comment]
> or give me the rights 

given

**Comment by raboof** [comment]
OK, I created the relevant secrets and added them to sonatype. I *think* I already have the permissions to publish to com.typesafe, so let's give this a try.

**Comment by raboof** [comment]
Hmm, `error [Sonatype] [MISSING_PROFILE] Profile com.typesafe.sbt is not found. Check your sonatypeProfileName setting in build.sbt`

**Comment by raboof** [comment]
> Hmm, `error [Sonatype] [MISSING_PROFILE] Profile com.typesafe.sbt is not found. Check your sonatypeProfileName setting in build.sbt`

fixed in 228ad032eb7095dbf7c16b16684a57716a9a0e03, released 1.0.1 from CI https://repo1.maven.org/maven2/com/typesafe/sbt/sbt-git_2.12_1.0/1.0.1/

**Pull request merged**
